name: Auto Generation of Docs

on:
  push:
    branches:
      - gh-pages
jobs:
  autodoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git merge origin/develop
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx_rtd_theme
    - name: Update Documentation
      run: |
        cd sphinx
        sphinx-apidoc -f --ext-autodoc -o . ../isv/
        make html
        cd ..
        cp -a sphinx/_build/html/. docs/
    - name: push to repo
      run: |
        git add .
        git commit -m 'ghactions: update documentation'
        git push

